### ISSUE TITLE
Decide on locking eth functions while flash minting

### ISSUE THREAD

**Issue by albertocuestacanada** [wETH-v2/WETH10#30]
I locked the eth functions while flash minting as a precaution, but it's that needed? Should we just assert that the eth balance is equal or greater than the weth supply at the end of a flash mint?

The lock uses 5K gas, so removing it would be great. 

On the other hand, could anything be broken with a billion dollars worth of ETH?

**Comment by PaulRBerg** [comment]
I would err on the side of caution with the flash mint function. If you're borrowing a few million dollars worth of ETH, you should be happy to pay a premium of 5,000 gas for additional security.

It's not just about attackers - what if there's a compiler bug that only works when the function is called recursively? A lock ensures that reentrancy is not possible no matter what.

**Comment by albertocuestacanada** [comment]
The lock doesn't protect the flash minter, and reentrancy is not a problem there either. The lock protects other contracts that could be broken by flash minting WETH and unwrapping it to Eth up to the totalSupply limit.

You yourself actually gave a great example of that in [this issue](https://github.com/wETH-v2/wETH-v2/issues/35). Developers need to be now aware that anyone could flash mint WETH, but developers were not aware in the past that flash minting ETH would be possible.

Locking `withdraw` during a flash mint protects these older contracts.

I would argue also that the users of these older contracts should see the writing on the wall and migrate to flash-mint-resistant version.

**Comment by albertocuestacanada** [comment]
I think that we could go for no locks, but a flash mint limit on the eth total supply. Thoughts?
